### PR TITLE
Feature logout

### PR DESCRIPTION
**Pull request by bestwebua**
Hi, Austin! Thanks for this awesome tutorial, it was very helpful for me. Please review my simple implementation of user logout feature.

### CODE REVIEW

**Comment by akabiru** [comment]
Hey @bestwebua , thanks for the PR! Sorry for the delay; wanted to let you know I'll have a look. 🙂

**Comment by bestwebua** [comment]
Thank you, @akabiru! Waiting for your feedback :)

**Review by akabiru — COMMENTED** [review]
Hey @bestwebua , really sorry for delaying on this- I've had a bit on my plate. 🙈 

Really like the implementation; I'm not sure I can merge it just yet as it would involve some bit of rewrite of the tutorial. Also, I've been looking at [JWT Revoke](http://waiting-for-dev.github.io/blog/2017/01/24/jwt_revocation_strategies/) strategies as an alternative? Curious what your thoughts are on that as well.

**Comment by bestwebua** [comment]
Hi, Austin! Thanks for your answer. This one and even more has implemented in ```jwt_sessions``` gem: https://github.com/tuwukee/jwt_sessions You can leave everything as it is :wink: , or write your own implementation completely. But is it make a sense? Maybe better idea is use ```jwt_sessions``` in your app?

**Comment by akabiru** [comment]
> Hi, Austin! Thanks for your answer. This one and even more has implemented in `jwt_sessions` gem: https://github.com/tuwukee/jwt_sessions You can leave everything as it is 😉 , or write your own implementation completely. But is it make a sense? Maybe better idea is use `jwt_sessions` in your app?

Hey Vladislav, that's a great idea! I've used it before on another [project](https://github.com/akabiru/idea_pool/blob/master/app/controllers/sessions_controller.rb) and it worked really well.

Would you be interested in collaborating on this one? 🙂

**Comment by bestwebua** [comment]
Yup, man :+1: Where I can find todo list? I will start it in my free time.

**Comment by akabiru** [comment]
Hey @bestwebua , I wanted to personally thank you for your contribution. It's a shame we weren't able to see the logout system fully out including the tutorial. I don't have a lot of bandwidth to look after this project and hence I'm looking to archive it temporarily.

**Comment by bestwebua** [comment]
> Hey @bestwebua , I wanted to personally thank you for your contribution. It's a shame we weren't able to see the logout system fully out including the tutorial. I don't have a lot of bandwidth to look after this project and hence I'm looking to archive it temporarily.

No problem, Austin! Cheers.

**Pull request closed without merging**
